### ISSUE TITLE
Get default value from BehaviorSubject

### ISSUE THREAD

**Issue by alshdavid** [darkartur/use-rxjs#1]
use the `getValue()` method to grab the value from a BehaviorSubject and use it to set the initial state value.

**Comment by darkartur** [comment]
@alshdavid thank you for issue. I am going to cover this case with unit test and fix it today.

**Comment by darkartur** [comment]
@alshdavid What kind of issue do u have? I wrote a few tests around this case and looks like everything working as expected. U can see spec here https://github.com/darkartur/use-rxjs/blob/master/src/index.spec.tsx. Anyway typescript overload have been added to useRxJs function for proper value type inference when using BehaviourSubject. I've released v0.0.3 with typings fix.

**Comment by darkartur** [comment]
@alshdavid
